INSERT INTO `question` (`question`, `xp`, `category`) VALUES
('La Première Guerre mondiale a commencé en quelle année ?', '25', 'History'),
('Adolf Hitler est né dans quel pays?', '25', 'Histoire'),
('John F. Kennedy a été assassiné en:', '25', 'Histoire'),
('Qui a combattu dans la guerre de 1812?', '75', 'Histoire'),
('Quel général a déclaré "Je reviendrai?', '25', 'Histoire'),
('La Magna Carta a été publiée par le roi de quel pays?', '25', 'Histoire'),
('La première presse à imprimer réussie a été développée par cet homme.', '25', 'Histoire'),
('La maladie qui a ravagé et tué un tiers de la population européenne au XIVe siècle est connue sous le nom de:', '75', 'Science'),
('La guerre de Cent Ans a été menée entre quels deux pays?', '25', 'Histoire'),
('Quel homme a écrit un document connu sous le nom des 95 thèses?', '25', 'Histoire'),
('Quel célèbre conquérant du 5ème siècle A.D était connu comme "Le fléau de Dieu?"', '25', 'Histoire'),
('Quel fusil célèbre est connu en Amérique comme "Le pistolet qui a gagné l’Occident?"', '75', 'Histoire'),
('Qui a écrit "Être, ou ne pas être, telle est la question"?', '25', 'Art') ,
('Selon les records du monde Guinness, quel est le livre le plus vendu de tous les temps?', '25', 'Art'),
('Quel type de verre est utilisé dans les films et les effets spéciaux de télévision pour briser, sans nuire aux acteurs?', '25', 'Art'),
('La "Nuit étoilée" de Van Gogh illustre la vue depuis la fenêtre de quel bâtiment', '75', 'Art'),
('Quel compositeur a son cœur enterré en Pologne et son corps enterré en France?', '75', 'Art'),
('Qui est Stefani Joanne Angelina Germanotta?', '75', 'Art'),
('Quel peintre continue son travail malgré l’arthrite invalidante?', '75', 'Art'),
('La Giaconda est mieux connu comme quoi?', '25', 'Art'),
('Tom Hanks a remporté deux Oscars consécutifs en 1994 et 1995. Pour quels films ?', '75', 'Art'),
('Qui a joué le rôle principal dans le film Lara Croft : Tomb Raider?', '25', 'Art'),
('Quel chanteur a le plus de singles UK Number One jamais?', '75', 'Art') ,
('Comment s’appelait le premier single de Britney Spears ?', '75', 'Art'),
('Quelle est la plus haute montagne du monde?', '25', 'Géographie'),
('Combien d’îles appartiennent aux Philippines?', '75', 'Géographie'),
('Lequel de ces pays a plus d’un capital?', '25', 'Géographie'),
('Où est la plus grande pyramide du monde?', '25', 'Géographie'),
('Comment les Îles Marshall ont-elles obtenu son nom?', '75', 'Géographie'),
('Quel est le nom de la deuxième plus grande cascade du monde, située en Afrique du Sud?', '75', 'Géographie'),
('Dans quelle ville se trouve la statue du "Christ Rédempteur"?', '25', 'Géographie'),
('Quelle ville est la capitale de l’Australie?', '25', 'Géographie'),
('Quel est le plus petit Etat du monde?', '25', 'Géographie'),
('Quelle ville turque a le nom d’un personnage de dessin animé?', '75', 'Géographie'),
('Quel pays avait autrefois le nom Rhodésie?', '75', 'Géographie'),
('Quel est le plus grand Etat des Etats-Unis?', '75', 'Géographie'),
('Quelle partie du corps a la peau la plus mince?', '25', 'Science'),
('Lequel de ces produits chimiques se trouve souvent dans le dissolvant de vernis à ongles?', '25', 'Science'),
('Où est le pharynx dans le corps humain?', '25', 'Science'),
('Combien de dents un humain adulte a-t-il?', '25', 'Science'),
('Quelle créature a la plus longue grossesse?', '75', 'Science'),
('Quel animal a plus d’un cœur?', '25', 'Science'),
('Qui a été la première femme à remporter le prix Nobel?', '75', 'Science'),
('Où est le plus petit os du corps humain?', '25', 'Science'),
('Que sont les phosphènes?', '75', 'Science'),
('Quelle plante, connue comme «porteuse d’espoir» a survécu à la bombe atomique d’Hiroshima en 1945?', '75', 'Science'),
('Quelle hormone fait que les cellules absorbent le glucose du sang?', '25', 'Science'),
('Quel animal marin est la seule créature mâle qui se reproduit par l’ovulation de la femelle?', '75', 'Science'),
('En quelle année Maradona a-t-il marqué un but avec sa main?', '75', 'Sports'),
('Combien de minutes est un match de rugby?', '75', 'Sports'),
('Dans quel pays ont eu lieu les premiers Jeux Olympiques?', '25', 'Sports'),
('Combien de matchs Mohammed Ali a-t-il perdu dans sa carrière ?', '75', 'Sports'),
('Quel cycliste s’appelait aussi "Le Cannibale"?', '75', 'Sports'),
('Dans quel pays se trouve le circuit F1 d’Interlagos ?', '75', 'Sports'),
('Quel est le nom du stade de football du FC Barcelone ?', '25', 'Sports'),
('Quelle méthode de fitness populaire a été inventée par un Allemand?', '75', 'Sports'),
('Combien de fois Michael Schumacher a-t-il été champion de Formule 1 ?', '75', 'Sports'),
('Quel est le sport national au Japon?', '25', 'Sports'),
('Avec quelle voiture Fernando Alonso a-t-il remporté son premier titre en Formule 1?', '75', 'Sports'),
('Quel joueur de billard est surnommé "The Rocket"?', '25', 'Sports');

INSERT INTO `answer` (`answer`, `correct`, `question_id`) VALUES
('1923', 0, 1),
('1938', 0, 1),
('1917', 0, 1),
('1914', 1, 1),
('France',0,2),
('Germany',0,2),
('Austria',1,2),
('Hungary',0,2),
('New York',0,3),
('Austin',0,3),
('Dallas',1,3),
('Miami',0,3),
('Andrew Jackson',1,4),
('Arthur Wellsley',0,4),
('Otto von Bismarck',0,4),
('Napoleon',0,4),
('Bull Halsey',0,5),
('George Patton',0,5),
('Douglas MacArthur',1,5),
('Omar Bradley',0,5),
('France',0,6),
('Austria',0,6),
('Italy',0,6),
('England',1,6),
('Johannes Gutenberg',1,7),
('Benjamin Franklin',0,7),
('Sir Isaac Newton',0,7),
('Martin Luther',0,7),
('The White Death',0,8),
('The Black Plague',0,8),
('Smallpox',0,8),
('The Bubonic Plague',1,8),
('Italy and Carthage',0,9),
('England and Germany',0,9),
('France and England',1,9),
('Spain and France',0,9),
('Martin Luther',1,10),
('Saint Augustus',0,10),
('Henry David Thoreau',0,10),
('Voltaire',0,10),
('Hannibal',0,11),
('Julius Caesar',0,11),
('William the Conqueror',0,11),
('Attila the Hun',1,11),
('Henry Repeating Rifle',0,12),
('Colt Peacemaker',0,12),
('Winchester Model 1873',1,12),
('Remington Army Revolver',0,12),
('Sylvia Plath', 0, 13),
('Virginia Woolf', 0, 13),
('John Steinbeck', 0, 13),
('William Shakespeare', 1, 13),
('The Three Musketeers', 0, 14),
('The Bible', 1, 14),
('Quotations from Chairman Mao Tse-tung', 0, 14),
('Quran', 0, 14),
('Barley glass', 0, 15),
('Sugar cup', 1, 15),
('Synthetic glass', 0, 15),
('Vinegar glass', 0, 15),
('Windmill', 0, 16),
('Hospital', 0, 16),
('Asylum', 1, 16),
('Hotel', 0, 16),
('Franz Liszt', 0, 17),
('Richard Wagner', 0, 17),
('Frédéric Chopin', 1, 17),
('Antonín Dvorak', 0, 17),
('Marilyn Monroe', 0, 18),
('Lady Gaga', 1, 18),
('Alicia Keys', 0, 18),
('Lana Del Rey', 0, 18),
('Pierre-Auguste Renoir', 1, 19),
('Pablo Picasso', 0, 19),
('Claude Monet', 0, 19),
('Miguel Ângelo', 0, 19),
('Meisje met de parel', 0, 20),
('Whistler\'s Mother', 0, 20),
('The Princesse de Broglie', 0, 20),
('Mona Lisa', 1, 20),
('"Philadelphia" and "Forrest Gump"', 1, 21),
('"Philadelphia" and "Salving Private Ryan"', 0, 21),
('"Salving Private Ryan" and "Cast Away"', 0, 21),
('"Cast Away" and "Forrest Gump"', 0, 21),
('Charlize Theron', 0, 22),
('Nicole Kidman', 0, 22),
('Angelina Jolie', 1, 22),
('Cameron Diaz', 0, 22),
('The Beatles', 0, 23),
('Madonna', 0, 23),
('Elvis Presley', 1, 23),
('Ed Sheeran', 0, 23),
('Baby One More Time', 1, 24),
('Toxic', 0, 24),
('Lucky', 0, 24),
('Born to Make You Happy', 0, 24),
('K2', 0, 25),
('Mount Everest', 1, 25),
('Mount Fuji', 0, 25),
('Kilimanjaro', 0, 25),
('184', 0, 26),
('10363', 0, 26),
('5290', 0, 26),
('7641', 1, 26),
('South Africa', 1, 27),
('Slovenia', 0, 27),
('Vietnam', 0, 27),
('Curaçao', 0, 27),
('Egypt', 0, 28),
('Mexico', 1, 28),
('Guatemala', 0, 28),
('Turkey', 0, 28),
('Hosted the first US Marshall Service', 0, 29),
('In honor of a famous Marshall', 0, 29),
('Due to the outline of the islands in the form of a great star', 0, 29),
('Were named after British explorer John Marshall', 1, 29),
('Tugela falls', 1, 30),
('Browne falls', 0, 30),
('Yosemite falls', 0, 30),
('James Bruce falls', 0, 30),
('Salvador', 0, 31),
('Rio de Janeiro', 1, 31),
('Brasília', 0, 31),
('São Paulo', 0, 31),
('Sydney', 0, 32),
('Melbourne', 0, 32),
('Adelaide', 0, 32),
('Camberra', 1, 32),
('Vatican', 1, 33),
('Monaco', 0, 33),
('Nauru', 0, 33),
('Tuvalu', 0, 33),
('Green Lantern', 0, 34),
('Batman', 1, 34),
('Wolverine', 0, 34),
('Spiderman', 0, 34),
('Madagascar', 0, 35),
('Zimbabwe', 1, 35),
('Kenya', 0, 35),
('Rwanda', 0, 35),
('California', 0, 36),
('Texas', 0, 36),
('Alaska', 1, 36),
('Washington', 0, 36),
('Eyelids', 1, 37),
('Feet soles', 0, 37),
('Hands', 0, 37),
('Arms', 0, 37),
('Dichloromethane', 0, 38),
('Acetone', 1, 38),
('Formalin', 0, 38),
('Butanol', 0, 38),
('Throat', 1, 39),
('Intestine', 0, 39),
('Ear', 0, 39),
('Eye', 0, 39),
('28', 0, 40),
('32', 1, 40),
('38', 0, 40),
('40', 0, 40),
('Giraffe', 0, 41),
('Elephant', 1, 41),
('Bison', 0, 41),
('Camel', 0, 41),
('Jellyfish', 0, 42),
('Blue whale', 0, 42),
('Octopus', 1, 42),
('Hippopotamus', 0, 42),
('Marie Curie', 1, 43),
('Sigrid Undset', 0, 43),
('Lorne Schindler', 0, 43),
('Irene Hemmingway', 0, 43),
('Foot', 0, 44),
('Hand', 0, 44),
('Chest', 0, 44),
('Ear', 1, 44),
('Luminous spots that we see when rubbing our eyes closed', 1, 45),
('A lung disease', 0, 45),
('An additive to increase the carbonation of a drink', 0, 45),
('Small openings in the solar ring', 0, 45),
('Trema Orientalis', 0, 46),
('Carpobrotus Chilensis', 0, 46),
('Acer Buergerianum', 0, 46),
('Gingko Biloba', 1, 46),
('Oxytocin', 0, 47),
('Insulin', 1, 47),
('Adrenaline', 0, 47),
('Epinephrine', 0, 47),
('Octopus', 0, 48),
('Seahorse', 1, 48),
('Jellyfish', 0, 48),
('Hermit Crab', 0, 48),
('1986', 1, 49),
('1967', 0, 49),
('1978', 0, 49),
('1990', 0, 49),
('90', 0, 50),
('80', 1, 50),
('70', 0, 50),
('60', 0, 50),
('Greece', 1, 51),
('Italy', 0, 51),
('France', 0, 51),
('China', 0, 51),
('3', 0, 52),
('1', 0, 52),
('5', 1, 52),
('6', 0, 52),
('Lance Armstrong', 0, 53),
('Bernard Hinault', 0, 53),
('Fausto Coppi', 0, 53),
('Eddy Merckx', 1, 53),
('Italy', 0, 54),
('Belgium', 0, 54),
('Brazil', 1, 54),
('Germany', 0, 54),
('Santiago Barnabéu', 0, 55),
('La Cartuja', 0, 55),
('RCDE Stadium', 0, 55),
('Camp Nou', 1, 55),
('Yoga', 0, 56),
('Pilates', 1, 56),
('Crossfit', 0, 56),
('Parkour', 0, 56),
('9', 0, 57),
('10', 0, 57),
('7', 1, 57),
('5', 0, 57),
('Judo', 0, 58),
('Sumo Wrestling', 1, 58),
('Karate', 0, 58),
('Akido', 0, 58),
('Ferrrari', 0, 59),
('HRT (Hispania Racing Team)', 0, 59),
('Renault', 1, 59),
('Lotus', 0, 59),
('Mark Selby', 0, 60),
('Ronnie O\'Sullivan', 1, 60),
('Judd Trump', 0, 60),
('Neil Robertson', 0, 60);
